config/routes.rb
Rails.application.routes.draw do
  # get 'bookmarks/new'
  # get 'lists/index'
  # get 'lists/show'
  # get 'lists/new'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  root to: "lists#index"
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resources :lists, only: [:index, :show, :new, :create, :destroy] do
    resources :bookmarks, only: [:new, :create]
  end

  resources :bookmarks, only: [:destroy]

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :comment, length: { minimum: 6 }
  validates :movie, uniqueness: { scope: :list }
end

app/models/list.rb
class List < ApplicationRecord
  validates :name, uniqueness: true, presence: true
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks, dependent: :destroy
  has_one_attached :photo
end

app/models/movie.rb
class Movie < ApplicationRecord
  validates :title, :overview, presence: true
  validates :title, uniqueness: true
  has_many :bookmarks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController

  def create
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new(bookmark_params)
    @movie = Movie.find(params[:bookmark][:movie_id])
    @bookmark.movie = @movie
    @bookmark.list = @list

    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list)
  end

  private
  
  def bookmark_params
    params.require(:bookmark).permit(:movie_id, :comment)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
    @list = List.new
  end

  def show
    @list = List.find(params[:id])
    @bookmarks = @list.bookmarks
    @bookmark = Bookmark.new
  end


  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy
    redirect_to lists_path
  end


  private

  def list_params
    params.require(:list).permit(:name, :photo)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/_form.html.erb
<%= simple_form_for [list, bookmark] do |f| %>
  <%= f.input :comment %>
  <%= f.association :movie, as: :select %>
  <%= f.button :submit, class: "btn btn-primary text-white" %>
<% end %>

app/views/bookmarks/new.html.erb
<div class="container">
  <h1>Add a movie to <%= @list.name %> List</h1>
  <%= render "form", list: @list, bookmark: @bookmark %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
<nav class="navbar sticky-top navbar-lewagon bg-primary">
  <span class="navbar-brand mb-0 h1 ms-4">
  <%= image_tag "movie-frame.png", width: 30 %>
  <span class="text-white ms-2">WatchList</span>
  </span>
  <div class="me-3 navbar-brand">
    <%= link_to "My lists", root_path, class: "btn me-3" %>
  </div>
</nav>

    <%= yield %>

  </body>
</html>

app/views/lists/_form.html.erb
<%= simple_form_for(@list) do |f| %>
  <%= f.input :name %>
  <%= f.input :photo, as: :file %>
  <%= f.button :submit, class: "btn btn-primary mb-3 text-white" %>
<% end %>

app/views/lists/index.html.erb
<div class="banner mb-4">
<h1>Keep track of your movie lists</h1>
</div>


<div class="container">

  <div class="list-head">
    <h2>My Lists</h2>
  </div>


  <div class="row mt-4">
    <% if @lists.length > 0 %>
      <% @lists.each do |list|%>
        <div class="col-4">
          <div class="card-list mb-4" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path list.photo.key%>')">
            <%= link_to list.name, list_path(list) %>
            <%= link_to list_path(list), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "card-remove-link" do %>
            <i class="fa-solid fa-xmark"></i>
            <% end %>
          </div>
        </div>
      <% end %>
    <% else %>
    <h4>You don't have any lists yet, add some below!</h4>
    <% end %>
  </div>

  <div class="row mt-5">
    <h3>Add a list</h3>
      <%= render "form", list: @list %>
    </div>
</div>

app/views/lists/new.html.erb
<div class="container">
<h1>Create a movie list</h1>
<%= render "form", list: @list %>

<%= link_to "Back", lists_path %>
</div>

app/views/lists/show.html.erb
<div class="banner mb-3" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path @list.photo.key%>')">
  <h1><%= @list.name %></h1>
</div>

<div class="container justify-content-center p-3">
  <div class="row mb-3">
      <% if @bookmarks.length > 0 %>
      <% @bookmarks.each do |bookmark| %>
      <div class="col-lg-4 col-md-6 col-12 d-flex align-items-stretch">
        <div class="card mb-3">
        <%= image_tag bookmark.movie.poster_url, alt: "movie poster", class: "card-img-top" %>
        <div class="card-body">
          <h5 class="card-title"><%= bookmark.movie.title %></h5>
          <p class="card-content"><%= bookmark.movie.overview %></p>
        </div>
        <div class="card-footer">
        <span>
        <i class="fa-solid fa-quote-left"></i> <%= bookmark.comment %>
        </span>
        <%= link_to bookmark_path(bookmark), data: {turbo_method: "delete", turbo_confirm: "Are you sure?"} do %>
          <i class="fa-regular fa-trash-can"></i>
        <% end %>
        </div>
        </div>
      </div>
      <% end %>
    <% else %>
      <h4>You have no movies in this list yet, add some below!</h4>
    <% end %>

  </div>
<div class="row mb-3">
<h2>Add a movie</h2>
<%= render "bookmarks/form", bookmark: @bookmark, list: @list %>
</div>

</div>